image:
  name: git.keithley.com:5050/trebuchet/teaspoon/teaspoon-build:latest
  entrypoint: [""]

include:
  # https://gitlab.com/gitlab-org/gitlab/-/tree/master/lib/gitlab/ci/templates/Workflows/MergeRequest-Pipelines.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml
  # - template: Security/SAST.gitlab-ci.yml
  # - template: Code-Quality.gitlab-ci.yml


cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
    - node_modules/

variables:
  # Uppercased versions of NPM config variables are valid,
  # but Node prefers lowercased variants.
  #   https://github.com/npm/npm/issues/14528
  npm_config_cache: ".npm"
  npm_config_prefer_offline: "true"
  NODE_EXTRA_CA_CERTS: "/etc/ssl/certs/ca-certificates.crt"

stages:
  - install
  - style
  - lint
  - compile
  - test
  - package
  - deploy


.npm-ci:
  before_script:
    # see https://gitlab.com/gitlab-org/gitlab/-/issues/352962
    - npm config set -- "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken" "${CI_JOB_TOKEN}"
    - npm ci --no-audit --ignore-scripts

.install:
  stage: .pre
  script:
    # Print toolchain versions.
    - node --version && npm --version
    # Make cache targets if they don't exist already.
    - mkdir -p .npm node_modules
    - npm config set -- "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken" "${CI_JOB_TOKEN}"
    # We want this to run in the "script" section,
    # so we don't extend the dedicated ".npm-ci" stage.
    - npm ci --no-audit --ignore-scripts

install:
  extends: .install

.style:
  stage: style
  when: always

style-prettier:
  extends:
    - .style
    - .npm-ci
  needs:
    - install
  script:
    - npx prettier --version
    - npx prettier --list-different .

.lint:
  stage: lint
  when: always

lint-eslint:
  extends:
    - .lint
    - .npm-ci
  needs:
    - install
  script:
    - npx eslint --version
    - 'npx eslint --rule "{ prettier/prettier: off }" src'

compile:
  stage: compile
  extends:
    - .npm-ci
  needs:
    - install
  script:
    - npm run compile
  artifacts:
    paths:
      - out/

test-mocha:
  extends:
    - .npm-ci
  stage: test
  needs:
    - compile
  script:
    - npx nyc --nycrc-path=.nycrc.json npm run test-ci
    - npx nyc report --reporter=cobertura --reporter=text
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

package-vsix:
  extends:
    - .npm-ci
  stage: package
  script:
    - npx vsce package --pre-release --baseContentUrl https://git.keithley.com/trebuchet/teaspoon/teaspoon/
    - cp *.vsix teaspoon.vsix
  needs:
    - compile
  artifacts:
    paths:
      - "*.vsix"

release:
  stage: deploy
  image: git.keithley.com:5050/gitlab-support/gitlab-release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - package-vsix
  script:
    # Remove the "v" from the version number THIS IS FRAGILE
    - export TEASPOON_COMMS_FILE="teaspoon-${CI_COMMIT_TAG:1}.vsix"
  release:
    tag_name: $CI_COMMIT_TAG
    name: "Teaspoon $CI_COMMIT_TAG release"
    description: |
      ## :warning: Disclaimer :warning:
      This is an _alpha_ stage project and should **NOT** be used for production use-cases.
      This project is **NOT** ready for customer usage. If there is a need to use this with a customer, please contact someone from the Teaspoon team to discuss options.

      ## Features Requests / Bugs
      If you find issues or have a feature request, please enter a [new issue on GitLab](https://git.keithley.com/trebuchet/teaspoon/teaspoon/-/issues/new).
      This will allow us to filter the issues into JIRA to avoid duplicates and keep things focused.

      ## Installation
      View the installation instructions [here](https://git.keithley.com/trebuchet/teaspoon/teaspoon/-/blob/dev/README.md#installation)

      ## Added Features
      - __TBD__

      ## Known Issues
      - __TBD__

    ref: "$CI_COMMIT_TAG"
    assets:
      links:
        - name: VSCode Extension Package
          url: "https://${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/${CI_COMMIT_REF_NAME}/raw/teaspoon.vsix?job=package-vsix"
          filepath: "/teaspoon.vsix"
          link_type: package
